name: dask_tutorial_env
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20200225.2
  - aiohttp=3.6.2
  - appnope=0.1.0
  - argon2-cffi=20.1.0
  - arrow-cpp=2.0.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.2.0
  - aws-c-common=0.4.59
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.70
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - blosc=1.20.0
  - bokeh=2.2.3
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - cryptography=3.1.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2.27.0
  - dask-core=2.27.0
  - dask-labextension=3.0.0
  - decorator=4.4.2
  - distributed=2.28.0
  - freetype=2.10.2
  - fsspec=0.8.0
  - gflags=2.2.2
  - glog=0.4.0
  - grpc-cpp=1.33.1
  - h5py=2.10.0
  - hdf5=1.10.4
  - heapdict=1.0.1
  - holoviews=1.13.5
  - idna=2.10
  - imageio=2.9.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2019.4
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jinja2=2.11.2
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-server-proxy=1.5.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lcms2=2.11
  - libcurl=7.71.1
  - libcxx=11.0.0
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgfortran=3.0.1
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libthrift=0.13.0
  - libtiff=4.1.0
  - libutf8proc=2.5.0
  - locket=0.2.0
  - lz4-c=1.9.2
  - lzo=2.10
  - markdown=3.3.2
  - markupsafe=1.1.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mock=4.0.2
  - msgpack-python=1.0.0
  - multidict=4.7.5
  - nbclient=0.5.0
  - nbconvert=6.0.7
  - nbformat=5.0.7
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - networkx=2.5
  - nodejs=10.13.0
  - notebook=6.1.4
  - numexpr=2.7.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1h
  - orc=1.6.5
  - packaging=20.4
  - pandas=1.1.2
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - panel=0.10.1
  - param=1.10.0
  - parquet-cpp=1.5.1
  - partd=1.1.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.4
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - psutil=5.7.2
  - pyarrow=2.0.0
  - pycparser=2.20
  - pyct=0.4.8
  - pyct-core=0.4.8
  - pygments=2.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyviz_comms=0.7.6
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - re2=2020.10.01
  - readline=8.0
  - requests=2.24.0
  - scikit-image=0.16.2
  - scipy=1.5.0
  - setuptools=50.3.0
  - simpervisor=0.3
  - six=1.15.0
  - snakeviz=2.0.1
  - snappy=1.1.8
  - sortedcontainers=2.2.2
  - sqlite=3.33.0
  - tblib=1.7.0
  - testpath=0.4.4
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.0.4
  - tqdm=4.50.2
  - traitlets=5.0.4
  - typing_extensions=3.7.4.3
  - urllib3=1.25.10
  - wcwidth=0.2.5
  - wheel=0.35.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.0
  - zeromq=4.3.2
  - zict=2.0.0
  - zipp=3.3.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - beautifulsoup4==4.9.3
    - bs4==0.0.1
    - currencyconverter==0.14.3
    - defusedxml==0.6.0
    - entrypoints==0.3
    - ipython-genutils==0.2.0
    - jupyterlab==2.2.8
    - parso==0.7.1
    - ptyprocess==0.6.0
    - pyzmq==19.0.2
    - send2trash==1.5.0
    - soupsieve==2.0.1
    - terminado==0.9.1
    - webencodings==0.5.1
    - wget==3.2
prefix: /opt/anaconda3/envs/dask_tutorial_env
